version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SenhaFuncionario!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  funcionario.api:
    container_name: funcionario.api
    image: ${DOCKER_REGISTRY-}funcionarioapi
    depends_on: 
      - db
    ports:
      - "9000:8080"
    build:
      context: .
      dockerfile: Funcionario.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  autenticacao.api:
    image: ${DOCKER_REGISTRY-}autenticacaoapi
    container_name: autenticacao.api
    depends_on: 
      - db
      - funcionario.api
    ports:
      - "9001:8080"
    build:
      context: .
      dockerfile: Autenticacao.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  sql_data:
